# 这是一个基本工作流程,可帮助您开始操作

名称: CI

控制工作流何时运行
上:
  # 在推送或拉取请求事件时触发工作流程,但仅适用于“主”分支
推:
分支机构: [ 主 ]
拉力请求:
分支机构: [ 主 ]

  # 允许您从“操作”选项卡手动运行此工作流
工作流程_调度:

# 工作流运行由一个或多个可按顺序或并行运行的工作组成
工作:
  # 此工作流包含一个名为“build”的单个工作
构建:
    # 作业将运行的跑步者类型
运行: 最新

    # 步骤表示将作为工作的一部分执行一系列任务
步骤:
      在 $GITHUB_WORKSPACE 下检查您的仓库,以便您的作业能够访问
      - 用途: 行动/结账@v4

      # 使用 runns shell 运行单个命令
      - 名称: 运行一行脚本
跑步: 回想一下,世界!

      # 使用 runs shell 运行一组命令
      - 名称: 运行一个多行脚本
跑步: |
回声 添加其他操作以构建,
回波测试,并部署您的项目。
